FROM registry.deez.re/research/python-audio-gpu

# install requirements
COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt
COPY . /tmp/


# env variable
ENV RESEARCH_CODE=/src_code

# set work directory
WORKDIR $RESEARCH_CODE


ENV PYTHONPATH=$PYTHONPATH:$RESEARCH_CODE

# Avoid default access to all GPU
ENV CUDA_VISIBLE_DEVICES=3

ENTRYPOINT ["bash" ,"-c","source $DATARD_PATH/research_setenv.sh.dev;$SHELL"]


